name: accom_validation_server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
dependencies: 
  encrypt: ^5.0.1
  path: ^1.8.0
  pointycastle: ^3.4.0
  process: ^4.2.4
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
